USE `agent`

CREATE TABLE `GoAgent` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`ip` VARCHAR(15) NOT NULL DEFAULT '',
	`name` VARCHAR(40) NOT NULL DEFAULT '',
	PRIMARY KEY(`id`)
);

CREATE TABLE `GoLog` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`agent_id` INT NOT NULL,
	`isOK` TINYINT(1) DEFAULT 0,
	`message` VARCHAR(255) DEFAULT '',
	`last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(`id`)
)
